[CI] adding ce demos testing

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -17,6 +17,127 @@ jobs:
       - name: Run ah lint
         working-directory: ./charts/mlrun-ce
         run: ah lint
+
+  ci-runner:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: Extract private key
+      run: echo "${{ secrets.MLRUN_PEM }}" > mlrun.pem
+    - name: Set permissions on key
+      run: chmod 400 mlrun.pem
+    - name: Install sshpass
+      run: sudo apt-get install -y sshpass
+    - name: Copy pem to remote machine
+      run: |
+        sudo scp -r -o StrictHostKeyChecking=no -i mlrun.pem  /home/runner/work/ce ${{ secrets.USERNAME }}@${{ secrets.IP }}:/home/${{ secrets.USERNAME }}/ce
+    - name: Cleaning instance
+      run: |
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        # CLEANUP
+        echo "helm uninstall mlrun-ce"
+        helm uninstall -n mlrun mlrun-ce || echo true
+        echo "helm uninstall monitoring"
+        helm uninstall -n mlrun monitoring || echo true
+        echo "delete pv, pvc from mlrun"
+        kubectl delete all --all -n mlrun
+        echo "deleting mlrun namepsace";
+        kubectl delete namespace mlrun || echo true
+        EOF
+        
+    - name: Creating mlrun namespace
+      run: |
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        echo "create mlrun namepsace"
+        kubectl create namespace mlrun        
+        echo "k8s namespaces - $(kubectl get namespace)"
+        EOF
+        
+    - name: Creating docker registry secret
+      run: |
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        kubectl --namespace mlrun create secret docker-registry registry-credentials \
+        --docker-server ${{ secrets.DOCKER_SERVER }} \
+        --docker-username ${{ secrets.DOCKER_USERNAME }} \
+        --docker-email=${{ secrets.DOCKER_EMAIL }} \
+        --docker-password=${{ secrets.DOCKER_PASSWORD }}
+        EOF
+
+    - name: CE installation
+      run: |    
+        # CE INSTALLATION
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        echo $(pwd)
+        cd ce/ce/charts/mlrun-ce
+        echo $(ls)
+        echo "helm dependency update"
+        helm dependency update
+        echo "installing community edition"
+        helm install mlrun-ce --namespace mlrun \
+        --set minio.resources.requests.memory="128Mi" \
+        --set  jupyterNotebook.persistence.size="1Gi" \
+        --set  mlrun.db.persistence.size="1Gi" \
+        --set  mlrun.api.persistence.size="1Gi" \
+        --set  mpi-operator.deployment.create="true" \
+        --set  mlrun.httpDB.dbType="sqlite" \
+        --set  mlrun.httpDB.dirPath="/mlrun/db" \
+        --set  mlrun.httpDB.dsn="sqlite:////mlrun/db/mlrun.db?check_same_thread=false"  \
+        --set  mlrun.httpDB.oldDsn=""  \
+        --set global.registry.url=${{ secrets.DOCKER_URL }}  --set global.registry.secretName=registry-credentials   \
+        --set global.externalHostAddress=${{ secrets.IP }}  \
+        --set nuclio.dashboard.externalIPAddresses[0]=${{ secrets.IP }}  \
+        --wait --debug --timeout=1h .
+        EOF
+
+    - name: Run demos from Jupyter pod notebook - news_article_nlp
+      uses: appleboy/ssh-action@v0.1.10
+      with:
+        host: ${{ secrets.IP }}
+        username: ${{ secrets.USERNAME }}
+        key: ${{ secrets.MLRUN_PEM }}
+        script: |
+          jupyter_service=$(kubectl -n mlrun get pods -o name | grep jupyter | head -n 1 | cut -d / -f 2)
+          kubectl exec -n mlrun $jupyter_service -- jupyter nbconvert --to notebook --execute /home/jovyan/demos/news-article-nlp/news_article_nlp.ipynb --ExecutePreprocessor.kernel_name=python3 --output=/home/jovyan/demos/mask-detection/1-news-article-nlp.ipynb
+
+    - name: Run demos from Jupyter pod notebook - 1-training-and-evaluation.ipynb
+      uses: appleboy/ssh-action@v0.1.10
+      with:
+        host: ${{ secrets.IP }}
+        username: ${{ secrets.USERNAME }}
+        key: ${{ secrets.MLRUN_PEM }}
+        script: |
+          jupyter_service=$(kubectl -n mlrun get pods -o name | grep jupyter | head -n 1 | cut -d / -f 2)
+          kubectl exec -n mlrun $jupyter_service -- jupyter nbconvert --to notebook --execute /home/jovyan/demos/mask-detection/1-training-and-evaluation.ipynb --ExecutePreprocessor.kernel_name=python3 --output=/home/jovyan/demos/mask-detection/1-training-and-evaluation.ipynb
+
+
+    - name: Run demos from Jupyter pod notebook - 2-serving.ipynb
+      uses: appleboy/ssh-action@v0.1.10
+      with:
+        host: ${{ secrets.IP }}
+        username: ${{ secrets.USERNAME }}
+        key: ${{ secrets.MLRUN_PEM }}
+        script: |
+          jupyter_service=$(kubectl -n mlrun get pods -o name | grep jupyter | head -n 1 | cut -d / -f 2)
+          kubectl exec -n mlrun $jupyter_service -- jupyter nbconvert --to notebook --execute /home/jovyan/demos/mask-detection//home/jovyan/demos/mask-detection/2-serving.ipynb --ExecutePreprocessor.kernel_name=python3 --output=/home/jovyan/demos/mask-detection/2-serving.ipynb
+
+    - name: Run demos from Jupyter pod notebook - 3-automatic-pipeline.ipynb
+      uses: appleboy/ssh-action@v0.1.10
+      with:
+        host: ${{ secrets.IP }}
+        username: ${{ secrets.USERNAME }}
+        key: ${{ secrets.MLRUN_PEM }}
+        script: |
+          jupyter_service=$(kubectl -n mlrun get pods -o name | grep jupyter | head -n 1 | cut -d / -f 2)
+          kubectl exec -n mlrun $jupyter_service -- jupyter nbconvert --to notebook --execute /home/jovyan/demos/mask-detection/3-automatic-pipeline.ipynb --ExecutePreprocessor.kernel_name=python3 --output=/home/jovyan/demos/mask-detection/3-automatic-pipeline.ipynb
+
+    - name: Deleting junk
+      run: |
+        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
+        rm -rf /home/ubuntu/ce
+        EOF
+        rm -rf mlrun.pem
+
   # commented out for now, takes too long to pull images
   # perhaps we can invoke it via workflow dispatch or as a nightly job
   # test:
