CEML-381: Add GitHub Actions workflow for triggering private deployments

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,6 +38,19 @@ jobs:
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
+      - name: Extract Chart Version from Chart.yaml
+        id: extract_version
+        run: |
+          CHART_VERSION=$(grep '^version:' charts/mlrun-ce/Chart.yaml | awk '{print $2}')
+          if [[ -z "$CHART_VERSION" ]]; then
+            echo "Error: Failed to extract version from Chart.yaml" >&2
+            exit 1
+          fi
+          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT
+
+    outputs:
+      version: ${{ steps.extract_version.outputs.version }}
+
   notify_mlefi:
     runs-on: ubuntu-latest
     needs: release # Ensure this runs after the release job
@@ -73,3 +86,13 @@ jobs:
             -H "Authorization: token ${{ secrets.MLEFIGHTRIGGER }}" \
             https://api.github.com/repos/iguazio/mlefi/dispatches \
             -d "$JSON_PAYLOAD"
+
+  deploy_ce_onprem:
+    needs: release
+    uses: ./.github/workflows/deploy_ce_onprem_public.yaml
+    with:
+      version: ${{ needs.release.outputs.version }}
+    secrets:
+      DEPLOYMENT_TRIGGER_TOKEN: ${{ secrets.DEPLOYMENT_TRIGGER_TOKEN }}
+      SYSTEM_ID: ${{ secrets.SYSTEM_ID }}
+      TEST_PARAMS: ${{ secrets.TEST_PARAMS }}
